test_blog/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',
        views.post_list,
        name='post_list'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),

    url(r'^like/$',
        views.post_like,
        name='post_like'),

    url(r'^search/$',
        views.post_search,
        name='post_search'),
]

test_blog/test_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^account/', include('account.urls')),

    url(r'^', include('blog.urls', namespace='blog', app_name='blog')),
]

test_blog/blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Post(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',
                                        blank=True)

    total_likes = models.PositiveIntegerField(db_index=True, default=0)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:  # when no slug is provided
            self.slug = slugify(self.title)  # generate the image slug for the given title
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='post_comments')
    user = models.ForeignKey(User, related_name='users_comments')
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.user.email, self.post)

test_blog/blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class SearchForm(forms.Form):
    query = forms.CharField()

test_blog/blog/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .models import Post
from .forms import CommentForm, SearchForm


@login_required
def post_list(request):
    object_list = Post.objects.all()
    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts})


@login_required
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    comments_list = post.post_comments.all()
    paginator = Paginator(comments_list, 3)
    page = request.GET.get('page')

    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            new_comment.save()
            messages.success(request, 'Your comment has been added.')

    comment_form = CommentForm()

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'comment_form': comment_form,
                   'page': page})


@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')

    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass

    return JsonResponse({'status': 'ko'})


@login_required
def post_search(request):
    context = {'search_form': SearchForm()}
    if 'query' in request.GET:
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            cd = search_form.cleaned_data
            keyword = cd['query']
            posts = Post.objects.filter(body__icontains=keyword)
            context['keyword'] = keyword
            context['posts'] = posts

    return render(request,
                  'blog/post/search_results.html',
                  context)

test_blog/templates/blog/post/detail.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <a href="{% url "blog:post_list" %}">< back</a>
    <div class="panel panel-default">
        <div class="panel-body">
            <h2>{{ post.title }}</h2>
            {{ post.body|linebreaks }}
        </div>
        <div class="panel-footer"><em>Published {{ post.publish }} by {{ post.author }}</em></div>
    </div>

    {% with total_likes=post.users_like.count users_like=post.users_like.all %}
        <div class="image_info">

            <div>
                <span class="count">
                    <span class="total">{{ total_likes }}</span>
                    like{{ total_likes|pluralize }}
                </span>

                <button type="button" class="btn btn-default" aria-label="Left Align">
                    <span class="glyphicon glyphicon-heart" aria-hidden="true">
                        <a href="#" data-id="{{ post.id }}"
                           data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
                            {% if request.user not in users_like %}
                                Like
                            {% else %}
                                Unlike
                            {% endif %}
                        </a>
                    </span>
                </button>


            </div>

            {{ image.description|linebreaks }}
        </div>

    {% endwith %}

    <h2>
        comments section:
    </h2>

    {% include "pagination.html" with page=comments %}

    {% for comment in comments %}
        <div class="well">
            <p class="info">
                <em>Comment by {{ comment.user.email }}
                    ({{ comment.created }})</em>
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    <h2>Add a new comment</h2>
    <form method="post">
        {% for field in comment_form %}
            {{ field }}
        {% endfor %}
        {% csrf_token %}
        <p><input type="submit" class="btn btn-default" value="Add comment"></p>
    </form>

    <a href="{% url "blog:post_list" %}">< back</a>
{% endblock %}

{% block domready %}
    $('a.like').click(function(e){
    e.preventDefault();
    $.post(
    '{% url "blog:post_like" %}',
    {
    id: $(this).data('id'),
    action: $(this).data('action')
    },
    function(data) {
    if (data['status'] == 'ok') {
    var previous_action = $('a.like').data('action');
    var previous_likes = parseInt($('span.count .total').text());

    if (previous_action == 'like') {

    $('a.like').data('action', 'unlike');
    $('a.like').text('Unlike');
    $('span.count .total').text(previous_likes + 1);

    } else {

    $('a.like').data('action', 'like');
    $('a.like').text('Like');
    $('span.count .total').text(previous_likes - 1);

    }

    }
    }
    );
    });
{% endblock %}

test_blog/templates/blog/post/list.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <a href="{% url "blog:post_search" %}">
        <h3>search by keyword</h3>
    </a>
    <br>
    {% for post in posts %}
        <div class="panel panel-default">
            <div class="panel-body">
                <h3 class="text-center">
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h3>
                <p class="text-center"><em>Published {{ post.publish }} by {{ post.author }}</em></p>
                {{ post.body|truncatewords:30|linebreaks }}
            </div>
        </div>
    {% endfor %}

    {% include "pagination.html" with page=posts %}
{% endblock %}

test_blog/templates/blog/post/search_results.html
{% extends "base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <a href="{% url "blog:post_list" %}">< back</a>

    <div class="panel panel-primary">
        <div class="panel-heading"><h4>Search by keyword:</h4></div>
        <div class="panel-body">
            <form method="get">
                {% csrf_token %}
                {{ search_form.as_p }}
                <button type="submit">search</button>
            </form>
        </div>
    </div>
    <br>
    {% if keyword %}
        <h2>Search with keyword = {{ keyword }}</h2>
        {% if posts %}
            {% for post in posts %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h3 class="text-center">
                            <a href="{{ post.get_absolute_url }}">
                                {{ post.title }}
                            </a>
                        </h3>
                        <p class="text-center"><em>Published {{ post.publish }} by {{ post.author }}</em></p>
                        {{ post.body|truncatewords:30|linebreaks }}
                    </div>
                </div>
            {% endfor %}

        {% else %}
            <h2>No result.</h2>
        {% endif %}
    {% endif %}
{% endblock %}